-- Migration 000: Baseline v3 → v4 (Niumination Mission Control Aether)
--
-- KENAPA PERLU MIGRASI INI
-- 001_initial.sql memakai `CREATE TABLE IF NOT EXISTS`. Kalau DB sudah punya
-- tabel v3 (agents/tasks/cost_tracking/dispatches/system_logs), statement itu
-- DILEWATI — tapi statement CREATE INDEX setelahnya tetap jalan dan gagal:
--
--   CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON tasks(assigned_agent);
--   → SQLITE_ERROR: no such column: assigned_agent
--
-- Skema v3 vs v4 tidak kompatibel:
--   tasks : v3 punya `agent_id`; v4 pakai `assigned_agent` (nama berubah)
--           v3 tidak punya 14 kolom lifecycle v4
--   agents: v3 tidak punya description/adapter/system_prompt/enabled/created_at
--
-- ══════════════════════════════════════════════════════════════════
-- ⚠️ BACA DULU — kenapa file ini tidak berisi ALTER TABLE
--
-- SQL tidak punya `ALTER TABLE IF EXISTS`, dan SQLite tidak punya trigger
-- `BEFORE ALTER` (dicek 26 Sep 2026: `CREATE TRIGGER ... BEFORE ALTER ON t`
-- → syntax error). Jadi statement ALTER tidak bisa dibuat conditional di
-- dalam file .sql.
--
-- Solusi: file ini hanya berisi transformasi DATA (idempoten, aman di DB
-- kosong maupun DB v3), dan part 1/2 (perubahan SKEMA) dilakukan runner
-- `lib/server/db.ts` lewat `ensureV3Columns()` yang mengecek keberadaan
-- tabel/kolom sebelum ALTER.
--
-- Efek sampingnya bagus: file ini aman dijalankan di DB kosong (install baru)
-- maupun di DB v3 (upgrade), jadi tidak perlu dihapus manual seperti
-- catatan versi sebelumnya.
--
-- Urutan: 001_initial.sql → ensureV3Columns() → 000 (data) → 002 (index).
-- Lihat lib/server/db.ts runMigrations().

-- ══════════════════════════════════════════════════════════════════
-- TASKS: status v3 pending → v4 inbox
-- ══════════════════════════════════════════════════════════════════
-- ⚠️ Sengaja TIDAK ditulis di file ini: `UPDATE tasks` akan error
-- "no such table: tasks" di DB yang belum punya tabel (install baru).
-- Lihat ensureV3Columns() di lib/server/db.ts — semua transformasi data
-- v3→v4 dilakukan di sana dalam blok yang dicek keberadaan tabelnya.
-- File ini sengaja hanya berisi komentar, bukan statement.

-- Ringkasan transformasi data (dikerjakan oleh ensureV3Columns):
--   tasks          : status 'pending' → 'inbox'
--   agents         : status 'active'  → 'idle'
--   agents         : adapter chief 'hermes' → 'mock'
--   cost_tracking  : created_at disalin ke recorded_at
--
-- Kenapa chief → mock: seed v4 memakai adapter 'mock' supaya development
-- jalan tanpa Hermes CLI terinstall. DB v3 punya 'hermes' untuk semua agent
-- → worker claim task lalu menggantung (Hermes CLI tidak tersedia, dan tidak
-- ada retry: next_retry_at NULL). Empat agent lain tetap 'hermes', sama
-- seperti seed v4.
