/**
 * POST /api/auth/setup  — first-run setup (only works saat isSetupRequired() = true).
 * Setelah ini dipanggil, operator harus set environment variables:
 *   MC_PASSWORD_HASH  (output dari script / hashPassword)
 *   MC_API_KEY        (api key untuk programmatic access)
 *   MC_SESSION_SECRET (untuk production)
 *
 * Endpoint ini tidak bisa dipakai jika setup sudah selesai.
 *
 * Untuk kemudahan dev, endpoint ini juga BISA dipakai untuk mereset password
 * jika MC_ALLOW_RESET=1 (hanya untuk development).
 */

import crypto from 'crypto'
import { getSession, hashPassword, generateApiKey } from '@/lib/server/auth'
import { config, isSetupRequired } from '@/lib/server/env'
import { publicHandler, json, parseBody, ApiError } from '@/lib/server/api-helpers'
import { z } from 'zod'
import fs from 'fs'
import path from 'path'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

const SetupSchema = z.object({
  password: z.string().min(6, 'Password must be at least 6 characters'),
})

export const GET = publicHandler(async () => {
  return json({
    setupRequired: isSetupRequired(),
    allowReset: process.env.MC_ALLOW_RESET === '1',
  })
})

export const POST = publicHandler(async (req) => {
  if (!isSetupRequired() && process.env.MC_ALLOW_RESET !== '1') {
    throw new ApiError(403, 'Setup already completed. Set MC_ALLOW_RESET=1 to enable reset.')
  }

  const body = await parseBody(req, SetupSchema)
  const passwordHash = await hashPassword(body.password)
  const apiKey = generateApiKey()
  const sessionSecret = crypto.randomBytes(32).toString('hex')

  // Tulis ke .env.local jika writable (untuk dev)
  // Di production user copy nilai dari response ke env mereka sendiri.
  const envLocalPath = path.resolve(process.cwd(), '..', '.env.local')
  const envLines = [
    '# Niumination Mission Control — generated by setup',
    `# Generated at: ${new Date().toISOString()}`,
    `MC_PASSWORD_HASH=${passwordHash}`,
    `MC_API_KEY=${apiKey}`,
    `MC_SESSION_SECRET=${sessionSecret}`,
    '',
    '# Opsional: uncomment dan sesuaikan',
    '# HERMES_CLI=/usr/local/bin/hermes',
    '# HERMES_TELEGRAM_CHAT_ID=-100xxxxxxxxx',
    '# MC_BIND=127.0.0.1',
    '# PORT=3000',
    '',
  ]
  try {
    fs.writeFileSync(envLocalPath, envLines.join('\n'), { encoding: 'utf-8', mode: 0o600 })
    console.log(`[setup] Wrote credentials to ${envLocalPath}`)
  } catch (e) {
    console.warn('[setup] Could not write .env.local (maybe permission denied). Silakan set manual.', e)
  }

  // Log in langsung
  const session = await getSession()
  session.loggedIn = true
  session.loggedInAt = new Date().toISOString()
  await session.save()

  return json({
    success: true,
    message: 'Setup completed. Restart aplikasi untuk memuat credentials baru.',
    credentials: {
      apiKey,
      passwordHash,
      sessionSecret,
    },
    note: 'Simpan API key ini di tempat aman. API key tidak bisa dilihat lagi setelah ini (karena disimpan sebagai hash/secret).',
  })
})
